### ISSUE TITLE
V12 Compatibility

### ISSUE THREAD

**Issue by cryptiklemur** [RichardRobertson/update-your-password#1]
Hi! Can you please update this to work with V12?

**Comment by RichardRobertson** [comment]
Completed with https://github.com/RichardRobertson/update-your-password/commit/5b486a0131d80347ede6ef73094af156b4764072

Version 2.0.0 available at https://foundryvtt.com/packages/update-your-password

**Comment by RichardRobertson** [comment]
I only did a quick verification that it did show the dialog and update the password so the code hasn't really changed. If you do encounter any errors don't be afraid to reach out.
