### ISSUE TITLE
Feature Request: Allow users to open the Update Password Dialog from a Foundry script or macro

### ISSUE THREAD

**Issue by dementedhedgehog** [RichardRobertson/update-your-password#2]
**Description**
Enable opening the password dialog from a foundry macro or script.   Add documentation to describe how this functionality can be used from a Foundry VTT Macro or Script.

**Use case**
It makes more senses to me that the this functionality lives in a Landing Page rather than hidden away in the menu.   

**Interface Changes**
Expose a call(s) to the foundry scripting api to toggle and/or show/hide/query-visibility of the Update Password Dialog.

**Additional Context**

## Progress Status
- [x] Code committed
- [x] Testing - QA
- [x] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by RichardRobertson** [comment]
The update password dialog is not exposed outside of the module. This is just how JavaScript works.

Would you like to make this a feature request instead of a question?

**Comment by dementedhedgehog** [comment]
Good enough?

**Comment by dementedhedgehog** [comment]
Thank you.  Works well!
