### ISSUE TITLE
Plugin does not seem to be working in VTT 12 build 331

### ISSUE THREAD

**Issue by alandsidel** [RichardRobertson/update-your-password#3]
Installed this (2.1.0) today but neither the icon nor context menu are showing up after activating, when logged in as a test user granted ownership of an actor.

This is with VTT 12 stable, build 331.  D&D game module 4.0.4.  Updating to 4.1.1 did not address the issue.

There are other modules installed, but I don't think they should conflict.

  - two custom modules (actor & journal)
  - carousel combat tracker
  - dice so nice
  - dice tray
  - file picker tweaks
  - libwrapper
  - monk's active tile triggers
  - popout
  - tokenizer
  - vision 5e

I looked around the config settings and permissions as well and didn't see anything there that I thought I should activate or change.

**Comment by RichardRobertson** [comment]
I appreciate the details on your environment, however when I set up a fresh D&D 5e world on Foundry 12.331 with all those modules loaded, I can see the right click menu in the user list when right clicking the signed in user. I can see it on both the Gamemaster and an additional normal user.

Can you confirm whether or not you see this in your Gamemaster account's "Configure Settings" menu?

![image](https://github.com/user-attachments/assets/7646b140-18d7-4ef8-9f45-35a34c70f70f)

**Comment by alandsidel** [comment]
Yep, that setting is enabled.  Here is a short video clip of checking the settings as GM then looking for the option as the player.

https://github.com/user-attachments/assets/9abdc8cd-01bc-44a9-9dc9-af66872606d2

**Comment by RichardRobertson** [comment]
Ah, I see where the confusion lies.
1. You have the option for "Show token controls tool item" unchecked which is the default state.
2. The "Show user context menu item" is added to the right click menu of the "Players" list, not the actors list. This is the list in the bottom left of your video.

Does this help?

**Comment by alandsidel** [comment]
> Ah, I see where the confusion lies.
> 
>   1. You have the option for "Show token controls tool item" unchecked which is the default state.
> 
>   2. The "Show user context menu item" is added to the right click menu of the "Players" list, not the actors list. This is the list in the bottom left of your video.
> 
> 
> Does this help?

Ahhh!  Yes, indeed the option is there.  Thanks!  Can close this, sorry for the trouble.

**Comment by RichardRobertson** [comment]
Wonderful. Enjoy your tabletop!
